### ISSUE TITLE
Small bug in bodies inheritance

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#759]
🐞 **Problem**

While working with SSO orbits I discovered a bug 🐞

```python
Earth.angular_velocity
```

Following error is raised:

```bash
AttributeError: '_Earth' object has no attribute 'angular_velocity'
```

This is because `Earth` inherits from `_Earth` and this one from `_Body` instead of `Body`, loosing last attributes introduced in #746 . Same error will be raised with other SS bodies.

📋  **Steps to solve the problem**

Inherit different private Solar System bodies classes from `Body` instead of `_Body` :rocket:

**Comment by Juanlu001** [comment]
This was fixed in #763.
